<?php
/**
 *Ejemplo de calculo de factorial.
 */

 /**
  *Implements hook_menu().
  */
 
 function ww_factorial_menu(){
 $items['calculo/factorial']=array(
    'title' => "Calculando factorial",
    'description' => t('This is a test.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('operation_factorial_form'),
    'access callback' => TRUE,
    'file' => 'ww_factorial_operacion.inc',
    );
 return $items;
 }