<?php

/**
 * @file
 * Este modulo es exclusivamente para crear campos y widgets.
 *
 * Aqui tambien se añadio el trabajo con JQuery.
 */



/**
 * Implements hook_field_widget_info();
 */
function ww_campos_field_widget_info() {
  return array(
    'ww_link' => array(
      'label' => t('Link'),
      'field types' => array('text'),
    ),
    'ww_chosen' => array(
      'label' => t('mi chosen'),
      'field types' => array('list_text'),
    ),
  );
}

/**
 * Implements hook_field_widget_form();
 */
function ww_campos_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $main_widget = array();
  switch ($instance['widget']['type']) {
    case 'ww_link':

      $main_widget = $element + array(
        '#type' => 'textfield',
        '#default_value' => isset($items[$delta]['value']) ? $items[$delta]['value'] : NULL,
        '#size' => 30,
        '#maxlength' => 100,
        '#attributes' => array('class' => array('text-full')),
      );
      break;
    case 'ww_chosen':
      $value_key = key($field['columns']);

      $type = str_replace('options_', '', $instance['widget']['type']);
      $multiple = $field['cardinality'] > 1 || $field['cardinality'] == FIELD_CARDINALITY_UNLIMITED;
      $required = $element['#required'];
      $has_value = isset($items[0][$value_key]);
      $properties = _options_properties($type, $multiple, $required, $has_value);

      $entity_type = $element['#entity_type'];
      $entity = $element['#entity'];

      // Prepare the list of options.
      $options = _options_get_options($field, $instance, $properties, $entity_type, $entity);

      // Put current field values in shape.
      $default_value = _options_storage_to_form($items, $options, $value_key, $properties);

      $path = drupal_get_path("module", "ww_campos");
      $main_widget = $element + array(
        '#type' => 'select',
        '#default_value' => $default_value,
        // '#prefix' => '<div class="side-by-side clearfix">',
        //'#suffix' => '</div>',
        // Do not display a 'multiple' select box if there is only one option.
        '#multiple' => $multiple && count($options) > 1,
        '#options' => $options,
        '#attributes' => array(
          'class' => array('chosen-select-deselect'),
          'style' => 'width: 200px',
        ),
      );
      drupal_add_library("ww_campos", "chosen");
      drupal_add_js($path . "/agregando_chosen.js", array('scope' => 'footer'));
      break;
  }
  if ($main_widget) {
    // Conditionally alter the form element's type if text processing is enabled.
    if (isset($instance['settings']['text_processing'])) {
      $element = $main_widget;
      $element['#type'] = 'text_format';
      $element['#format'] = isset($items[$delta]['format']) ? $items[$delta]['format'] : NULL;
      $element['#base_type'] = $main_widget['#type'];
    }
    else {
      $element['value'] = $main_widget;
    }
  }
  return $element;
}

/**
 * Implements hook_field_formatter_info();
 */
function ww_campos_field_formatter_info() {
  return array(
    'ww_link' => array(
      'label' => t('link fields'),
      'field types' => array('text'),
    ),
    'ww_colorbox' => array(
      'label' => t('mi colorbox'),
      'field types' => array('image'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view();
 */
function ww_campos_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $path = drupal_get_path("module", "ww_campos");
  switch ($display['type']) {

    case 'ww_link':
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => l(strip_tags($item['value']), $item['value']));
      }
      break;
    case 'ww_colorbox':
      drupal_add_library("ww_campos", "colorbox");

      drupal_add_js($path . "/agregar_colorbox.js");

      foreach ($items as $delta => $item) {

        $direccion = file_create_url($item['uri']);

        $element[$delta] = array(
          '#theme' => 'image_formatter',
          '#prefix' => '<p><a id="group1" href="' . $direccion . '" title="Mi imagen en colorbox">',
          '#item' => $item,
          '#image_style' => 'miEstiloImage',
          '#suffix' => '</a></p>',
        );
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_library();
 */
function ww_campos_library() {
  $libraries['colorbox'] = array(
    'title' => 'Libreria de colorbox',
    'website' => 'http://www.jacklmoore.com/colorbox/',
    'version' => '1.4.34',
    'js' => array(
      drupal_get_path('module', 'ww_campos') . '/colorbox/jquery.colorbox.js' => array(),
    ),
    'css' => array(
      drupal_get_path('module', 'ww_campos') . '/colorbox/example1/colorbox.css' => array(),
    ),
  );
  $libraries['chosen'] = array(
    'title' => 'Libreria de chosen',
    'website' => 'https://github.com/harvesthq/chosen/releases/download/v1.1.0/chosen_v1.1.0.zip',
    'version' => '1.1.0',
    'js' => array(
      drupal_get_path('module', 'ww_campos') . '/chosen/chosen.jquery.js' => array(),
    ),
    'css' => array(
      drupal_get_path('module', 'ww_campos') . '/chosen/chosen.css' => array(),
    //drupal_get_path('module', 'ww_campos') . '/chosen/docsupport/estilo.css' => array(),
    ),
  );
    $libraries['ui.datepicker'] = array(
    'title' => 'jQuery UI: Date Picker',
    'website' => 'http://jqueryui.com/demos/datepicker/',
    'version' => '1.8.7',
    'js' => array(
      'misc/ui/jquery.ui.datepicker.min.js' => array(),
    ),
    'css' => array(
      'misc/ui/jquery.ui.datepicker.css' => array(),
    ),
    'dependencies' => array(
      array('system', 'ui'),
    ),
  );
  return $libraries;
}
