<?php
/**
 * @file
 * En este archivo se configuran las opciones de instalacion y desinstalacion.
 *
 * Para este caso solo se eliminan las variables que fueron
 * creadas en el modulo.
 */

/**
 * Implements hook_uninstall();
 */
function conversorutm_uninstall() {

  variable_del('excentricidad');
  variable_del('excentricidad2');
  variable_del('curvatura_radio_polar');
  variable_del('UTM_X');
  variable_del('UTM_Y');
  variable_del('Huso');
}
